name: Kali-Linux

on: 
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout Kali-Linux
         uses: actions/checkout@main
       
       - name: "Duplicate Workflow Runs"
         uses: styfle/cancel-workflow-action@0.9.0
         with:
            all_but_latest: true
            access_token: ${{ github.token }}
       - name: Initialization Kali-Linux
         continue-on-error: true
         run: |
           git config --global user.name ${{ secrets.GIT_NAME }}
           git config --global user.email ${{ secrets.GIT_EMAIL }}
           git config --global credential.helper store
           echo "https://${{ secrets.GIT_NAME }}:${{ secrets.GIT_TOKEN }}@github.com" > ~/.git-credentials
       - name: Cloning Repository
         continue-on-error: true
         uses: actions/checkout@master
         with:
           repository: ${{ secrets.BOT_REPO }}
       - name: Running Kali-Linux Server
         timeout-minutes: 350
         continue-on-error: true
         run: |
           docker build . -t tele-vps
           docker run --env CONFIG_FILE_URL=${{ secrets.CONFIG_FILE_URL }} tele-vps
       - name: Loop Kali-Linux Server
         continue-on-error: true
         run: |
              git clone https://github.com/${GITHUB_REPOSITORY} loop
              cd loop || exit 1
              echo $(date -u +%T%P) >> loop.txt
              git add loop.txt
              git commit -m "Kali-Linux : Loop $(date -u +%D-%T%P)"
              git push -q https://${{ secrets.GIT_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:Kali-Linux
